# 端口号
server:
  port: 8082
# 应用名字
spring:
  application:
    name: service-cnm
  profiles:
    active: dev
    # mysql怕配置文件
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_cmn?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123123
#日期设置
  jackson:
    date-format: yyyy-MM-dd HH :mm:ss
    time-zone: GMT+8
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  cloud: #nacos配置
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
